name: midtrans_plugin
description: "A Flutter plugin for integrating Midtrans payment gateway into your applications."
version: 1.0.0
repository: https://github.com/deytri/midtrans_plugin

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=3.3.0"

dev_dependencies:
  melos: ^6.2.0
  flutter_lints: ^4.0.0
